package edu.scu.hereis.dao;

import edu.scu.hereis.entity.Restaurant;
import edu.scu.hereis.entity.RestaurantExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RestaurantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    long countByExample(RestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    int deleteByExample(RestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    int deleteByPrimaryKey(Integer spotId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    int insert(Restaurant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    int insertSelective(Restaurant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    List<Restaurant> selectByExample(RestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") Restaurant record, @Param("example") RestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    int updateByExample(@Param("record") Restaurant record, @Param("example") RestaurantExample example);
}