package edu.scu.hereis.dao;

import edu.scu.hereis.entity.ScenicSpot;
import edu.scu.hereis.entity.ScenicSpotExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScenicSpotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    long countByExample(ScenicSpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    int deleteByExample(ScenicSpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    int deleteByPrimaryKey(Integer spotId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    int insert(ScenicSpot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    int insertSelective(ScenicSpot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    List<ScenicSpot> selectByExample(ScenicSpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    ScenicSpot selectByPrimaryKey(Integer spotId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") ScenicSpot record, @Param("example") ScenicSpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    int updateByExample(@Param("record") ScenicSpot record, @Param("example") ScenicSpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    int updateByPrimaryKeySelective(ScenicSpot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenic_spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    int updateByPrimaryKey(ScenicSpot record);
}