package edu.scu.hereis.dao;

import edu.scu.hereis.entity.SchoolBuilding;
import edu.scu.hereis.entity.SchoolBuildingExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface SchoolBuildingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_building
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    long countByExample(SchoolBuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_building
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    int deleteByExample(SchoolBuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_building
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_building
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    int insert(SchoolBuilding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_building
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    int insertSelective(SchoolBuilding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_building
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    List<SchoolBuilding> selectByExample(SchoolBuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_building
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    SchoolBuilding selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_building
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") SchoolBuilding record, @Param("example") SchoolBuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_building
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    int updateByExample(@Param("record") SchoolBuilding record, @Param("example") SchoolBuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_building
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    int updateByPrimaryKeySelective(SchoolBuilding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_building
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    int updateByPrimaryKey(SchoolBuilding record);

    /**
     * This method was generated by Vicent_Chen.
     * This method corresponds to the database table school_building
     *
     * @param spotId
     * @return
     */
    Integer selectMaxFloorBySpotId(Integer spotId);
}