package edu.scu.hereis.entity;

import java.util.Date;

public class Activity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.spot_id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private Integer spotId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.intro
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.end_time
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.begin_time
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private Date beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.name
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.id
     *
     * @return the value of activity.id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.id
     *
     * @param id the value for activity.id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.spot_id
     *
     * @return the value of activity.spot_id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public Integer getSpotId() {
        return spotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.spot_id
     *
     * @param spotId the value for activity.spot_id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setSpotId(Integer spotId) {
        this.spotId = spotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.intro
     *
     * @return the value of activity.intro
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.intro
     *
     * @param intro the value for activity.intro
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.end_time
     *
     * @return the value of activity.end_time
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.end_time
     *
     * @param endTime the value for activity.end_time
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.begin_time
     *
     * @return the value of activity.begin_time
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.begin_time
     *
     * @param beginTime the value for activity.begin_time
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.name
     *
     * @return the value of activity.name
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.name
     *
     * @param name the value for activity.name
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}