package edu.scu.hereis.entity;

public class Course extends CourseKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_name
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.begin_time
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private Integer beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.end_time
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private Integer endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.sb_id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private Integer sbId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_name
     *
     * @return the value of course.course_name
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_name
     *
     * @param courseName the value for course.course_name
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.begin_time
     *
     * @return the value of course.begin_time
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public Integer getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.begin_time
     *
     * @param beginTime the value for course.begin_time
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setBeginTime(Integer beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.end_time
     *
     * @return the value of course.end_time
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public Integer getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.end_time
     *
     * @param endTime the value for course.end_time
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setEndTime(Integer endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.sb_id
     *
     * @return the value of course.sb_id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public Integer getSbId() {
        return sbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.sb_id
     *
     * @param sbId the value for course.sb_id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setSbId(Integer sbId) {
        this.sbId = sbId;
    }
}