package edu.scu.hereis.entity;

public class Menu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.price
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.category
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.name
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.img_path
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private String imgPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.spot_id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private Integer spotId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.id
     *
     * @return the value of menu.id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.id
     *
     * @param id the value for menu.id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.price
     *
     * @return the value of menu.price
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.price
     *
     * @param price the value for menu.price
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.category
     *
     * @return the value of menu.category
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.category
     *
     * @param category the value for menu.category
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.name
     *
     * @return the value of menu.name
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.name
     *
     * @param name the value for menu.name
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.img_path
     *
     * @return the value of menu.img_path
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.img_path
     *
     * @param imgPath the value for menu.img_path
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.spot_id
     *
     * @return the value of menu.spot_id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public Integer getSpotId() {
        return spotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.spot_id
     *
     * @param spotId the value for menu.spot_id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setSpotId(Integer spotId) {
        this.spotId = spotId;
    }
}