package edu.scu.hereis.entity;

public class Restaurant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.spot_id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private Integer spotId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.spot_id
     *
     * @return the value of restaurant.spot_id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public Integer getSpotId() {
        return spotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.spot_id
     *
     * @param spotId the value for restaurant.spot_id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setSpotId(Integer spotId) {
        this.spotId = spotId;
    }
}