package edu.scu.hereis.entity;

public class SchoolBuilding {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_building.id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_building.floor
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private Integer floor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_building.classroom
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private String classroom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_building.is_free
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private Boolean isFree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_building.classroom_type
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private String classroomType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_building.spot_id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private Integer spotId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_building.id
     *
     * @return the value of school_building.id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_building.id
     *
     * @param id the value for school_building.id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_building.floor
     *
     * @return the value of school_building.floor
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public Integer getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_building.floor
     *
     * @param floor the value for school_building.floor
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_building.classroom
     *
     * @return the value of school_building.classroom
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public String getClassroom() {
        return classroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_building.classroom
     *
     * @param classroom the value for school_building.classroom
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setClassroom(String classroom) {
        this.classroom = classroom == null ? null : classroom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_building.is_free
     *
     * @return the value of school_building.is_free
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public Boolean getIsFree() {
        return isFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_building.is_free
     *
     * @param isFree the value for school_building.is_free
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setIsFree(Boolean isFree) {
        this.isFree = isFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_building.classroom_type
     *
     * @return the value of school_building.classroom_type
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public String getClassroomType() {
        return classroomType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_building.classroom_type
     *
     * @param classroomType the value for school_building.classroom_type
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setClassroomType(String classroomType) {
        this.classroomType = classroomType == null ? null : classroomType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_building.spot_id
     *
     * @return the value of school_building.spot_id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public Integer getSpotId() {
        return spotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_building.spot_id
     *
     * @param spotId the value for school_building.spot_id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setSpotId(Integer spotId) {
        this.spotId = spotId;
    }
}