package edu.scu.hereis.entity;

public class Spot {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot.id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot.gps_lng
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private Double gpsLng;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot.gps_lat
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private Double gpsLat;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot.name
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot.brief_intro
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private String briefIntro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot.bg_img
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private String bgImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot.category
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    private String category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot.id
     *
     * @return the value of spot.id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot.id
     *
     * @param id the value for spot.id
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot.gps_lng
     *
     * @return the value of spot.gps_lng
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public Double getGpsLng() {
        return gpsLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot.gps_lng
     *
     * @param gpsLng the value for spot.gps_lng
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setGpsLng(Double gpsLng) {
        this.gpsLng = gpsLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot.gps_lat
     *
     * @return the value of spot.gps_lat
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public Double getGpsLat() {
        return gpsLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot.gps_lat
     *
     * @param gpsLat the value for spot.gps_lat
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setGpsLat(Double gpsLat) {
        this.gpsLat = gpsLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot.name
     *
     * @return the value of spot.name
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot.name
     *
     * @param name the value for spot.name
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot.brief_intro
     *
     * @return the value of spot.brief_intro
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public String getBriefIntro() {
        return briefIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot.brief_intro
     *
     * @param briefIntro the value for spot.brief_intro
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setBriefIntro(String briefIntro) {
        this.briefIntro = briefIntro == null ? null : briefIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot.bg_img
     *
     * @return the value of spot.bg_img
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public String getBgImg() {
        return bgImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot.bg_img
     *
     * @param bgImg the value for spot.bg_img
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setBgImg(String bgImg) {
        this.bgImg = bgImg == null ? null : bgImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot.category
     *
     * @return the value of spot.category
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot.category
     *
     * @param category the value for spot.category
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    @Override
    public String toString() {
        return "Spot{" +
                "id=" + id +
                ", gpsLng=" + gpsLng +
                ", gpsLat=" + gpsLat +
                ", name='" + name + '\'' +
                ", briefIntro='" + briefIntro + '\'' +
                ", bgImg='" + bgImg + '\'' +
                ", category='" + category + '\'' +
                '}';
    }
}