package edu.scu.hereis.entity;

import java.util.ArrayList;
import java.util.List;

public class SpotExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public SpotExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGpsLngIsNull() {
            addCriterion("gps_lng is null");
            return (Criteria) this;
        }

        public Criteria andGpsLngIsNotNull() {
            addCriterion("gps_lng is not null");
            return (Criteria) this;
        }

        public Criteria andGpsLngEqualTo(Double value) {
            addCriterion("gps_lng =", value, "gpsLng");
            return (Criteria) this;
        }

        public Criteria andGpsLngNotEqualTo(Double value) {
            addCriterion("gps_lng <>", value, "gpsLng");
            return (Criteria) this;
        }

        public Criteria andGpsLngGreaterThan(Double value) {
            addCriterion("gps_lng >", value, "gpsLng");
            return (Criteria) this;
        }

        public Criteria andGpsLngGreaterThanOrEqualTo(Double value) {
            addCriterion("gps_lng >=", value, "gpsLng");
            return (Criteria) this;
        }

        public Criteria andGpsLngLessThan(Double value) {
            addCriterion("gps_lng <", value, "gpsLng");
            return (Criteria) this;
        }

        public Criteria andGpsLngLessThanOrEqualTo(Double value) {
            addCriterion("gps_lng <=", value, "gpsLng");
            return (Criteria) this;
        }

        public Criteria andGpsLngIn(List<Double> values) {
            addCriterion("gps_lng in", values, "gpsLng");
            return (Criteria) this;
        }

        public Criteria andGpsLngNotIn(List<Double> values) {
            addCriterion("gps_lng not in", values, "gpsLng");
            return (Criteria) this;
        }

        public Criteria andGpsLngBetween(Double value1, Double value2) {
            addCriterion("gps_lng between", value1, value2, "gpsLng");
            return (Criteria) this;
        }

        public Criteria andGpsLngNotBetween(Double value1, Double value2) {
            addCriterion("gps_lng not between", value1, value2, "gpsLng");
            return (Criteria) this;
        }

        public Criteria andGpsLatIsNull() {
            addCriterion("gps_lat is null");
            return (Criteria) this;
        }

        public Criteria andGpsLatIsNotNull() {
            addCriterion("gps_lat is not null");
            return (Criteria) this;
        }

        public Criteria andGpsLatEqualTo(Double value) {
            addCriterion("gps_lat =", value, "gpsLat");
            return (Criteria) this;
        }

        public Criteria andGpsLatNotEqualTo(Double value) {
            addCriterion("gps_lat <>", value, "gpsLat");
            return (Criteria) this;
        }

        public Criteria andGpsLatGreaterThan(Double value) {
            addCriterion("gps_lat >", value, "gpsLat");
            return (Criteria) this;
        }

        public Criteria andGpsLatGreaterThanOrEqualTo(Double value) {
            addCriterion("gps_lat >=", value, "gpsLat");
            return (Criteria) this;
        }

        public Criteria andGpsLatLessThan(Double value) {
            addCriterion("gps_lat <", value, "gpsLat");
            return (Criteria) this;
        }

        public Criteria andGpsLatLessThanOrEqualTo(Double value) {
            addCriterion("gps_lat <=", value, "gpsLat");
            return (Criteria) this;
        }

        public Criteria andGpsLatIn(List<Double> values) {
            addCriterion("gps_lat in", values, "gpsLat");
            return (Criteria) this;
        }

        public Criteria andGpsLatNotIn(List<Double> values) {
            addCriterion("gps_lat not in", values, "gpsLat");
            return (Criteria) this;
        }

        public Criteria andGpsLatBetween(Double value1, Double value2) {
            addCriterion("gps_lat between", value1, value2, "gpsLat");
            return (Criteria) this;
        }

        public Criteria andGpsLatNotBetween(Double value1, Double value2) {
            addCriterion("gps_lat not between", value1, value2, "gpsLat");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andBriefIntroIsNull() {
            addCriterion("brief_intro is null");
            return (Criteria) this;
        }

        public Criteria andBriefIntroIsNotNull() {
            addCriterion("brief_intro is not null");
            return (Criteria) this;
        }

        public Criteria andBriefIntroEqualTo(String value) {
            addCriterion("brief_intro =", value, "briefIntro");
            return (Criteria) this;
        }

        public Criteria andBriefIntroNotEqualTo(String value) {
            addCriterion("brief_intro <>", value, "briefIntro");
            return (Criteria) this;
        }

        public Criteria andBriefIntroGreaterThan(String value) {
            addCriterion("brief_intro >", value, "briefIntro");
            return (Criteria) this;
        }

        public Criteria andBriefIntroGreaterThanOrEqualTo(String value) {
            addCriterion("brief_intro >=", value, "briefIntro");
            return (Criteria) this;
        }

        public Criteria andBriefIntroLessThan(String value) {
            addCriterion("brief_intro <", value, "briefIntro");
            return (Criteria) this;
        }

        public Criteria andBriefIntroLessThanOrEqualTo(String value) {
            addCriterion("brief_intro <=", value, "briefIntro");
            return (Criteria) this;
        }

        public Criteria andBriefIntroLike(String value) {
            addCriterion("brief_intro like", value, "briefIntro");
            return (Criteria) this;
        }

        public Criteria andBriefIntroNotLike(String value) {
            addCriterion("brief_intro not like", value, "briefIntro");
            return (Criteria) this;
        }

        public Criteria andBriefIntroIn(List<String> values) {
            addCriterion("brief_intro in", values, "briefIntro");
            return (Criteria) this;
        }

        public Criteria andBriefIntroNotIn(List<String> values) {
            addCriterion("brief_intro not in", values, "briefIntro");
            return (Criteria) this;
        }

        public Criteria andBriefIntroBetween(String value1, String value2) {
            addCriterion("brief_intro between", value1, value2, "briefIntro");
            return (Criteria) this;
        }

        public Criteria andBriefIntroNotBetween(String value1, String value2) {
            addCriterion("brief_intro not between", value1, value2, "briefIntro");
            return (Criteria) this;
        }

        public Criteria andBgImgIsNull() {
            addCriterion("bg_img is null");
            return (Criteria) this;
        }

        public Criteria andBgImgIsNotNull() {
            addCriterion("bg_img is not null");
            return (Criteria) this;
        }

        public Criteria andBgImgEqualTo(String value) {
            addCriterion("bg_img =", value, "bgImg");
            return (Criteria) this;
        }

        public Criteria andBgImgNotEqualTo(String value) {
            addCriterion("bg_img <>", value, "bgImg");
            return (Criteria) this;
        }

        public Criteria andBgImgGreaterThan(String value) {
            addCriterion("bg_img >", value, "bgImg");
            return (Criteria) this;
        }

        public Criteria andBgImgGreaterThanOrEqualTo(String value) {
            addCriterion("bg_img >=", value, "bgImg");
            return (Criteria) this;
        }

        public Criteria andBgImgLessThan(String value) {
            addCriterion("bg_img <", value, "bgImg");
            return (Criteria) this;
        }

        public Criteria andBgImgLessThanOrEqualTo(String value) {
            addCriterion("bg_img <=", value, "bgImg");
            return (Criteria) this;
        }

        public Criteria andBgImgLike(String value) {
            addCriterion("bg_img like", value, "bgImg");
            return (Criteria) this;
        }

        public Criteria andBgImgNotLike(String value) {
            addCriterion("bg_img not like", value, "bgImg");
            return (Criteria) this;
        }

        public Criteria andBgImgIn(List<String> values) {
            addCriterion("bg_img in", values, "bgImg");
            return (Criteria) this;
        }

        public Criteria andBgImgNotIn(List<String> values) {
            addCriterion("bg_img not in", values, "bgImg");
            return (Criteria) this;
        }

        public Criteria andBgImgBetween(String value1, String value2) {
            addCriterion("bg_img between", value1, value2, "bgImg");
            return (Criteria) this;
        }

        public Criteria andBgImgNotBetween(String value1, String value2) {
            addCriterion("bg_img not between", value1, value2, "bgImg");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNull() {
            addCriterion("category is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNotNull() {
            addCriterion("category is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryEqualTo(String value) {
            addCriterion("category =", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotEqualTo(String value) {
            addCriterion("category <>", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThan(String value) {
            addCriterion("category >", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("category >=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThan(String value) {
            addCriterion("category <", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThanOrEqualTo(String value) {
            addCriterion("category <=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLike(String value) {
            addCriterion("category like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotLike(String value) {
            addCriterion("category not like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryIn(List<String> values) {
            addCriterion("category in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotIn(List<String> values) {
            addCriterion("category not in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryBetween(String value1, String value2) {
            addCriterion("category between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotBetween(String value1, String value2) {
            addCriterion("category not between", value1, value2, "category");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table spot
     *
     * @mbg.generated do_not_delete_during_merge Fri Apr 20 16:26:09 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table spot
     *
     * @mbg.generated Fri Apr 20 16:26:09 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}