package edu.scu.hereis.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.hereis_id
     *
     * @mbg.generated Sat Jun 02 20:18:33 CST 2018
     */
    private String hereisId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.img_path
     *
     * @mbg.generated Sat Jun 02 20:18:33 CST 2018
     */
    private String imgPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.role
     *
     * @mbg.generated Sat Jun 02 20:18:33 CST 2018
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Sat Jun 02 20:18:33 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.hereis_id
     *
     * @return the value of user.hereis_id
     *
     * @mbg.generated Sat Jun 02 20:18:33 CST 2018
     */
    public String getHereisId() {
        return hereisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.hereis_id
     *
     * @param hereisId the value for user.hereis_id
     *
     * @mbg.generated Sat Jun 02 20:18:33 CST 2018
     */
    public void setHereisId(String hereisId) {
        this.hereisId = hereisId == null ? null : hereisId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.img_path
     *
     * @return the value of user.img_path
     *
     * @mbg.generated Sat Jun 02 20:18:33 CST 2018
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.img_path
     *
     * @param imgPath the value for user.img_path
     *
     * @mbg.generated Sat Jun 02 20:18:33 CST 2018
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.role
     *
     * @return the value of user.role
     *
     * @mbg.generated Sat Jun 02 20:18:33 CST 2018
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.role
     *
     * @param role the value for user.role
     *
     * @mbg.generated Sat Jun 02 20:18:33 CST 2018
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated Sat Jun 02 20:18:33 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated Sat Jun 02 20:18:33 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}